### ISSUE TITLE
some error when i compile

### ISSUE THREAD

**Issue by noticeable** [har-in-air/ESP32_IMU_BARO_GPS_VARIO#1]
hi ,
i want to compile your project in ubuntu.I have done to add arduino and make menuconfig like you say ,however,when I compile the project,I have met some error like this:
 /home/li/esp32/esp-idf/components/arduino/libraries/SPIFFS/src//SPIFFS.cpp:33:31: error: 'esp_spiffs_mounted' was not declared in this scope
     if(esp_spiffs_mounted(NULL)){
                               ^
/home/li/esp32/esp-idf/components/arduino/libraries/SPIFFS/src//SPIFFS.cpp:38:5: error: 'esp_vfs_spiffs_conf_t' was not declared in this scope
     esp_vfs_spiffs_conf_t conf = {
     ^
/home/li/esp32/esp-idf/components/arduino/libraries/SPIFFS/src//SPIFFS.cpp:45:46: error: 'conf' was not declared in this scope
     esp_err_t err = esp_vfs_spiffs_register(&conf);
                                              ^
/home/li/esp32/esp-idf/components/arduino/libraries/SPIFFS/src//SPIFFS.cpp:45:50: error: 'esp_vfs_spiffs_register' was not declared in this scope
     esp_err_t err = esp_vfs_spiffs_register(&conf);
                                                  ^
/home/li/esp32/esp-idf/components/arduino/libraries/SPIFFS/src//SPIFFS.cpp: In member function 'void fs::SPIFFSFS::end()':
/home/li/esp32/esp-idf/components/arduino/libraries/SPIFFS/src//SPIFFS.cpp:56:31: error: 'esp_spiffs_mounted' was not declared in this scope
     if(esp_spiffs_mounted(NULL)){
                               ^
/home/li/esp32/esp-idf/components/arduino/libraries/SPIFFS/src//SPIFFS.cpp:57:55: error: 'esp_vfs_spiffs_unregister' was not declared in this scope
         esp_err_t err = esp_vfs_spiffs_unregister(NULL);
                                                       ^
/home/li/esp32/esp-idf/components/arduino/libraries/SPIFFS/src//SPIFFS.cpp: In member function 'bool fs::SPIFFSFS::format()':
/home/li/esp32/esp-idf/components/arduino/libraries/SPIFFS/src//SPIFFS.cpp:68:43: error: 'esp_spiffs_format' was not declared in this scope
     esp_err_t err = esp_spiffs_format(NULL);
                                           ^
/home/li/esp32/esp-idf/components/arduino/libraries/SPIFFS/src//SPIFFS.cpp: In member function 'size_t fs::SPIFFSFS::totalBytes()':
/home/li/esp32/esp-idf/components/arduino/libraries/SPIFFS/src//SPIFFS.cpp:79:43: error: 'esp_spiffs_info' was not declared in this scope
     if(esp_spiffs_info(NULL, &total, &used)){
                                           ^
/home/li/esp32/esp-idf/components/arduino/libraries/SPIFFS/src//SPIFFS.cpp: In member function 'size_t fs::SPIFFSFS::usedBytes()':
/home/li/esp32/esp-idf/components/arduino/libraries/SPIFFS/src//SPIFFS.cpp:88:43: error: 'esp_spiffs_info' was not declared in this scope
     if(esp_spiffs_info(NULL, &total, &used)){
                                           ^
make[1]: *** [libraries/SPIFFS/src//SPIFFS.o] error1
make: *** [component-arduino-build] error2

I think may you know why this happen ,could you please give me some advice to solve the problems?
thx

**Comment by har-in-air** [comment]
Hi, good catch. Really should have kept notes when I started this project. I'm not using the Arduino SPIFFS library, and it was clashing with the SPIFFS code that I did use. So after including the Arduino component, I deleted the SPIFFS library directory from /arduino/libraries.
Hope this fixes the build issue for you - let me know - will update the README file.

**Comment by har-in-air** [comment]
The spiffs code is from https://github.com/loboris/ESP32_spiffs_example

You will also need to run 'make flashfs' once to create and save the spiffs partition image.

**Comment by noticeable** [comment]
thx for your answer.i have deleted the library as you say and compile the project ， then erro is  work gone,so i'll close this issue. this is a really good project in esp32. I want you know that I'm grateful for your share. 👍
