### ISSUE TITLE
Compiling on windows?

### ISSUE THREAD

**Issue by alejoal07** [har-in-air/ESP32_IMU_BARO_GPS_VARIO#5]
I've been trying to compile this on windows for days, finxing issue by issue but now I'm really stuck. 
When I try to Build Filesystem Image I get:

Building SPIFFS image from 'data' directory to .pio\build\esp32dev\spiffs.bin
'"C:\Users\Alejandro Desktop\Documents\PlatformIO\Projects\ESP32_IMU_BARO_GPS_VARIO-2.0-kf3_kf4\mklittlefs"' is not 
recognized as an internal or external command,
operable program or batch file.
*** [.pio\build\esp32dev\spiffs.bin] Error 1

Any way to fix this?
Thanks in advance

Alejandro

**Comment by har-in-air** [comment]
Sorry, I don't have a build environment on Windows. Have you tried downloading the binary for mklittlefs suitable for Windows from https://github.com/earlephilhower/mklittlefs/releases

**Comment by alejoal07** [comment]
Yes, thanks for the help, I indeed needed to download the .exe version of mklittlefs for it to work on windows, I will make sure to add a fork with everything included to compile and run from windows, thanks!
Couple of questions:
Is there going to be any further development? 
Is there any known bugs? 
How does this compare with the actual Xctracer? Do you have videos of this latest version working?

Best Regards and thank you for sharing!

**Comment by har-in-air** [comment]
Further development - possible, no plans.
Bugs - likely, reported - no
Don't have any videos of  vario  with latest KF4D algorithm, but it is a distinct improvement in terms of reducing noise in constant velocity situations while maintaining sensitivity
