### ISSUE TITLE
ringbuf_init() fails to clear the arena

### ISSUE THREAD

**Issue by mhaberler** [har-in-air/ESP32_IMU_BARO_GPS_VARIO#7]
https://github.com/har-in-air/ESP32_IMU_BARO_GPS_VARIO/blob/112ff89649b4ce1a4fc41984ccff6bdd61701ebf/src/sensor/ringbuf.cpp#L10

probably should say:
`````
  memset(RingBuf.buffer, 0, RINGBUF_SIZE * sizeof(float));
`````

thanks, really interesting code!

Michael

**Comment by har-in-air** [comment]
Fixed, thanks for the bug catch...
