### ISSUE TITLE
Wind sensor by GPS

### ISSUE THREAD

**Issue by rodrigomedeirosbrazil** [har-in-air/ESP32_IMU_BARO_GPS_VARIO#8]
Hi Hari!
Your project is awesome!

I'm developing a gps vario too, just for learn.

Checkout: https://github.com/rodrigomedeirosbrazil/flyby-gpsvario

I create a wind sensor using gps data, it's working good!
Try to use in your code.

**Comment by har-in-air** [comment]
Thanks !  Haven't been flying for a few years now, so the only changes I have made recently are things 
I can verify on the ground :-).

But if someone wants to fork the project and integrate your wind indicator, I will put a link to the project  on
my page.

**Comment by rodrigomedeirosbrazil** [comment]
Really? I can't stop flying! It's like a drug! I hope you be fine.
I will try to make a GPS Vario like your, using same hardware, and use I can your code. From there, I can improve and code new features.
